# Generated by Django 6.0.5 on 2026-05-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortalApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofilemodel',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
