# Generated by Django 6.0.5 on 2026-05-20 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortalApp', '0002_recruiterprofilemodel_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterprofilemodel',
            name='recruiter',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seekerprofilemodel',
            name='seeker',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seeker_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
